---
# This playbook deploys all site configs

- hosts: all
  tasks:
    - name: Set distribution vars
      include_vars: os_{{ ansible_os_family }}.yml

    # - debug:
    #     var: apache_pkg

- name: apply base configuration to all nodes
  hosts: all
  become: true

  roles:
  - base

- name: configure webservers
  hosts: webservers
  become: true

  roles:
  - webservers