---
# This playbook contains base plays for all nodes
- include_tasks: rhel-repos.yml
  when: ansible_os_family == "RedHat" and 
    (ansible_distribution_major_version == "8" or
    ansible_distribution_major_version == "7")

- name: Disable weak dependencies installation
  lineinfile:
    line: "install_weak_deps=False"
    state: present
    path: "/etc/dnf/dnf.conf"

- name: Install base packages
  yum: name="{{ base_packages }}" state=present install_weak_deps=no

- name: Start the firewalld service
  service: name=firewalld state=started enabled=yes

- name: Add users
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
  loop:
    - { name: "webadmin1", groups: ["wheel", "apache"] }
    - { name: "webadmin2", groups: "apache" }