---
# This playbook contains base plays for all nodes

- name: Disable weak dependencies installation
  lineinfile:
    line: "install_weak_deps=False"
    state: present
    path: "/etc/dnf/dnf.conf"

- name: Install base packages
  yum: name="{{ item }}" state=present install_weak_deps=no
  loop: "{{ base_packages }}"

- name: Start the firewalld service
  service: name=firewalld state=started enabled=yes