---
- name: Copy EPEL repo key
  copy:
    src: "RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

- name: Create EPEL repo file from template
  template:
    src: epel.repo.j2
    dest: /etc/yum.repos.d/epel.repo